markdownExploder: true
prd:
  prdFile: docs/developer/BMad-PRD.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/developer/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/developer/BMad-Architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/developer/architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/developer/architecture/coding-standards.md
  - docs/developer/architecture/tech-stack.md
  - docs/developer/architecture/source-tree.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/developer/stories
slashPrefix: BMad
